### ISSUE TITLE
UAA could not start as XM schema not created

### ISSUE THREAD

**Issue by ishkurko** [xm-online/xm-online#125]
**Steps to reproduce:**
Install XM^online locally via [instruction](https://github.com/xm-online/xm-online#installation-steps)

**Actual result:** The UAA could not start as XM schema not created.
Stacktrace from logs:
```
2019-04-30 16:03:25,504 ERROR [main] [NQTg3dEc::XM] XmSpringLiquibase: Failed to initialize default schema XM
liquibase.exception.LockException: liquibase.exception.DatabaseException: ERROR: schema "xm" does not exist
  Position: 14 [Failed SQL: CREATE TABLE xm.databasechangeloglock (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP WITHOUT TIME ZONE, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID))]
 	at liquibase.lockservice.StandardLockService.acquireLock(StandardLockService.java:242)
 	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:170)
```

**Expected result:** The UAA should start successfully.

**Comment by ishkurko** [comment]
Fixed.
