### ISSUE TITLE
Tenant Activation fails

### ISSUE THREAD

**Issue by joriqqq** [xm-online/xm-online#134]
Steps:
1) Run the app according readme.
2) Create new tenant on UI
3) Activate newly created tenant

Expected: tenant activated
Actual:  Activation failed

Response from: 
`GET Request URL: http://127.0.0.1/entity/api/xm-entities/951?embed=data`
```json

{
  "id": 951,
  "key": "87e507c5-2f24-3486-bed4-985a0c23f564",
  "typeKey": "RESOURCE.XM-TENANT",
  "stateKey": "ERROR",
  "name": "tc1",
  "startDate": "2020-04-16T14:24:34.276124Z",
  "updateDate": "2020-04-16T14:45:02.250261Z",
  "data": {
    "scheduler": {
      "create": {
        "success": false,
        "errorMessage": "com.netflix.client.ClientException: Load balancer does not have available server for client: scheduler"
      }
    },
    "uaa": {
      "create": {
        "success": true
      }
    },
    "balance": {
      "create": {
        "success": true
      }
    },
    "timeline": {
      "create": {
        "success": true
      }
    },
    "gate": {
      "create": {
        "success": true
      }
    },
    "entity": {
      "create": {
        "success": true
      }
    },
    "dashboard": {
      "create": {
        "success": true
      }
    }
  },
  "createdBy": "xm",
  "version": 10
}
```

Entity app log
`
2020-04-16 17:45:02,226 INFO  [XNIO-1 task-9] [SqvGrUz4:xm:XM] ServiceLoggingAspect: srv:start: XmEntityLifeCycleService:changeState, input: idOrKey=951,nextStateKey=ACTIVE,context={xmEntity={id=951, key=87e507c5-2f24-3486-bed4-985a0c23f564, typeKey=RESOURCE.XM-TENANT, stateKey=ERROR, name=tc1, startDate=2020-04-16T14:24:34.276Z, updateDate=2020-04-16T14:39:39.691Z, data={scheduler={create={success=false, errorMessage=com.netflix.client.ClientException: Load balancer does not have available server for client: scheduler}}, uaa={create={success=true}}, balance={create={success=true}}, timeline={create={success=true}}, gate={create={success=true}}, entity={create={success=true}}, dashboard={create={success=true}}}, createdBy=xm, version=8, endDate=null}}`

For the fix I assume scheduler should be made optional.

**Comment by joriqqq** [comment]
Starting new docker 

```yml
    scheduler-app:
        image: xmonline/xm-ms-scheduler:latest
        networks:
            - xm2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONSUL_HOST=consul
            - SPRING_CLOUD_CONSUL_PORT=8500
            - JHIPSTER_SLEEP=10
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
            - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
            - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=10
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/scheduler
            - SPRING_DATASOURCE_PASSWORD=postgres
```
gives this error
```
:: XM^online  :: Running version 2.0.0 :: Running Spring Boot 2.1.10.RELEASE :: https://xm.icthh.com ::

2020-04-16 19:08:55,769 INFO  [main] [HgQOVymo] SchedulerApp: The following profiles are active: prod,swagger
2020-04-16 19:09:02,620 INFO  [main] [HgQOVymo] WebConfigurer: Web application configuration, using profiles: prod
2020-04-16 19:09:02,632 INFO  [main] [HgQOVymo] WebConfigurer: Web application fully configured
2020-04-16 19:09:04,214 INFO  [main] [HgQOVymo] TenantListRepository: Tenants list was updated
2020-04-16 19:09:04,225 ERROR [main] [HgQOVymo] TenantListRepository: Tenant list for scheduler empty. Check tenants-list.json.
2020-04-16 19:09:04,227 WARN  [main] [HgQOVymo] AnnotationConfigServletWebServerApplicationContext: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'databaseConfiguration' defined in URL [jar:file:/app.war!/WEB-INF/classes!/com/icthh/xm/ms/scheduler/config/DatabaseConfiguration.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'schemaResolver' defined in URL [jar:file:/app.war!/WEB-INF/lib/xm-commons-migration-db-2.1.6.jar!/com/icthh/xm/commons/migration/db/tenant/SchemaResolver.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tenantListRepository' defined in class path resource [com/icthh/xm/commons/config/client/config/XmConfigTenantConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.icthh.xm.commons.config.client.repository.TenantListRepository]: Factory method 'tenantListRepository' threw exception; nested exception is java.lang.IllegalStateException: Tenant list for scheduler empty. Check tenants-list.json.
2020-04-16 19:09:04,256 ERROR [main] [HgQOVymo] SpringApplication: Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'databaseConfiguration' defined in URL [jar:file:/app.war!/WEB-INF/classes!/com/icthh/xm/ms/scheduler/config/DatabaseConfiguration.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'schemaResolver' defined in URL [jar:file:/app.war!/WEB-INF/lib/xm-commons-migration-db-2.1.6.jar!/com/icthh/xm/commons/migration/db/tenant/SchemaResolver.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tenantListRepository' defined in class path resource [com/icthh/xm/commons/config/client/config/XmConfigTenantConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.icthh.xm.commons.config.client.repository.TenantListRepository]: Factory method 'tenantListRepository' threw exception; nested exception is java.lang.IllegalStateException: Tenant list for scheduler empty. Check tenants-list.json.
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1187)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:392)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1321)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:307)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1105)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at com.icthh.xm.ms.scheduler.SchedulerApp.main(SchedulerApp.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:58)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'schemaResolver' defined in URL [jar:file:/app.war!/WEB-INF/lib/xm-commons-migration-db-2.1.6.jar!/com/icthh/xm/commons/migration/db/tenant/SchemaResolver.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tenantListRepository' defined in class path resource [com/icthh/xm/commons/config/client/config/XmConfigTenantConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.icthh.xm.commons.config.client.repository.TenantListRepository]: Factory method 'tenantListRepository' threw exception; nested exception is java.lang.IllegalStateException: Tenant list for scheduler empty. Check tenants-list.json.
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1187)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1255)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1175)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
	... 36 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tenantListRepository' defined in class path resource [com/icthh/xm/commons/config/client/config/XmConfigTenantConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.icthh.xm.commons.config.client.repository.TenantListRepository]: Factory method 'tenantListRepository' threw exception; nested exception is java.lang.IllegalStateException: Tenant list for scheduler empty. Check tenants-list.json.
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:607)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1321)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1255)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1175)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
	... 50 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.icthh.xm.commons.config.client.repository.TenantListRepository]: Factory method 'tenantListRepository' threw exception; nested exception is java.lang.IllegalStateException: Tenant list for scheduler empty. Check tenants-list.json.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
	... 64 common frames omitted
Caused by: java.lang.IllegalStateException: Tenant list for scheduler empty. Check tenants-list.json.
	at com.icthh.xm.commons.config.client.repository.TenantListRepository.assertExistTenants(TenantListRepository.java:164)
	at com.icthh.xm.commons.config.client.repository.TenantListRepository.updateTenants(TenantListRepository.java:117)
	at com.icthh.xm.commons.config.client.repository.TenantListRepository.onInit(TenantListRepository.java:187)
	at com.icthh.xm.commons.config.client.repository.TenantListRepository.<init>(TenantListRepository.java:70)
	at com.icthh.xm.commons.config.client.config.XmConfigTenantConfiguration.tenantListRepository(XmConfigTenantConfiguration.java:32)
	at com.icthh.xm.commons.config.client.config.XmConfigTenantConfiguration$$EnhancerBySpringCGLIB$$e2a7d6b0.CGLIB$tenantListRepository$0(<generated>)
	at com.icthh.xm.commons.config.client.config.XmConfigTenantConfiguration$$EnhancerBySpringCGLIB$$e2a7d6b0$$FastClassBySpringCGLIB$$7302947e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at com.icthh.xm.commons.config.client.config.XmConfigTenantConfiguration$$EnhancerBySpringCGLIB$$e2a7d6b0.tenantListRepository(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 65 common frames omitted

```
